language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
script: nosetests --with-coverage --cover-package=image_slicer
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
after_success:
  - coveralls
notifications:
  email: false

